# Generated by Django 3.2.12 on 2022-12-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
